run:
  name:        "default"
  description: "Default backtest configuration: BTCUSDT, 1h, 2025-01-01 to 2026-01-01"
  tags:        []

data:
  symbol:   BTCUSDT
  interval: 60
  start:    "2025-01-01" # "YYYY-MM-DD"
  end:      "2026-01-01" # "YYYY-MM-DD"

execution:
  fee_rate:             0.000550
  delay_bars:           1
  # Defaults:
    # fill_model:           "market"
    # mtm_price_type:       "mark"

risk:
  leverage_max: 1.0
  max_drawdown: 0.20
  max_position: 1.0

initial_capital: 100000

